name: Create ORT Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
         name: oss-review-toolkit/ort
         ref: refs/heads/main
    - name: Show
      run: docker images && ls -al 
