name: Create ORT Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: oss-review-toolkit/ort
        ref: main
    - uses: jimschubert/query-tag-action@v2
      with:
        abbrev: 10
        commit-ish: --always
      id: gittag
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: repo-name-adjusted
      name: Prepare repository name in lower case for docker upload. This supports repository names in mixed case
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}
    - run: DOCKER_BUILDKIT=1 docker build -t ghcr.io/${{ steps.repo-name-adjusted.outputs.lowercase }}/ort -t ghcr.io/${{ steps.repo-name-adjusted.outputs.lowercase }}/ort:${{steps.gittag.outputs.tag}} --build-arg ORT_VERSION=${{steps.gittag.outputs.tag}} .
    - name: Show
      run: docker images && ls -al 
    - run: docker push -a ghcr.io/${{ steps.repo-name-adjusted.outputs.lowercase }}/ort
